// Copyright 2024 wuzhanfly <wuzhanfly@gmail.com>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package entity

import (
	"github.com/wuzhanfly/ai-lib/app/model/entity/internal"
)

// WalletFlowGpt4 is the golang structure for table c_wallet_flow_gpt4.
type WalletFlowGpt4 internal.WalletFlowGpt4

// Fill with you ideas below.
